source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LETimeIntervalPicker_Example', :exclusive => true do
  pod "LETimeIntervalPicker", :path => "../"
end

target 'LETimeIntervalPicker_Tests', :exclusive => true do
  pod "LETimeIntervalPicker", :path => "../"

  
end
